### ISSUE TITLE
Example command: handle_message() got an unexpected keyword argument 'nickname'

### ISSUE THREAD

**Issue by syphernl** [silent1mezzo/jeeves-framework#27]
Running Jeeves with the default settings will cause traceback as soon as people send a command:

```
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/policies.py", line 118, in dataReceived
    self.wrappedProtocol.dataReceived(data)
  File "/usr/local/lib/python2.7/dist-packages/twisted/words/protocols/irc.py", line 2413, in dataReceived
    basic.LineReceiver.dataReceived(self, data.replace('\r', ''))
  File "/usr/local/lib/python2.7/dist-packages/twisted/protocols/basic.py", line 564, in dataReceived
    why = self.lineReceived(line)
  File "/usr/local/lib/python2.7/dist-packages/twisted/words/protocols/irc.py", line 2421, in lineReceived
    self.handleCommand(command, prefix, params)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/words/protocols/irc.py", line 2465, in handleCommand
    method(prefix, params)
  File "/usr/local/lib/python2.7/dist-packages/twisted/words/protocols/irc.py", line 1937, in irc_PRIVMSG
    self.privmsg(user, channel, message)
  File "/usr/local/lib/python2.7/dist-packages/jeeves/core/bot.py", line 32, in privmsg
    self.handler.message(user, channel, msg)
  File "/usr/local/lib/python2.7/dist-packages/jeeves/core/handlers/base.py", line 60, in message
    plugin.handle_message(channel=channel, nickname=user, message=message)
exceptions.TypeError: handle_message() got an unexpected keyword argument 'nickname'
```

**Comment by silent1mezzo** [comment]
Thanks for the catch. I totally forgot about the example plugin. It'll fix this today
